doctrine:
    dbal:
        driver: 'pdo_pgsql'
        # Utilisation de la variable d'environnement DATABASE_URL pour la configuration de la base de données
        url: '%env(resolve:DATABASE_URL)%'
        charset: 'UTF8'
        server_version: '%env(DATABASE_SERVER_VERSION)%'  # Optionnel, tu peux également configurer ça dans l'URL ou l'environnement

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        # Configuration de l'ORM
        auto_generate_proxy_classes: true  # Active en développement, désactive en production
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

# Spécifique à l'environnement de test
when@test:
    doctrine:
        dbal:
            logging: true  # Active le logging pour les tests
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'  # Utilise une variable d'environnement TEST_TOKEN pour suffixer le nom de la base de données pour les tests

# Spécifique à l'environnement de production
when@prod:
    doctrine:
        dbal:
            # Désactivation des logs en production
            logging: false
        orm:
            # En production, désactive la génération automatique des proxies et configure les caches
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app  # Pool pour le cache des résultats de Doctrine
                doctrine.system_cache_pool:
                    adapter: cache.system  # Pool pour le cache système de Doctrine
